openapi: 3.0.0
info:
  title: DummyJSON Products API
  version: 1.0.0
servers:
  - url: https://dummyjson.com
paths:
  /products:
    get:
      summary: Get all products
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Limit the number of results
        - in: query
          name: skip
          schema:
            type: integer
          description: Skip a number of results
      responses:
        '200':
          description: A list of products
  /products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single product
  /products/search:
    get:
      summary: Search products by keyword
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search query
      responses:
        '200':
          description: Search results
